<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>

<form id="wholesale-form">
    <fieldset class="fieldset-own-class">
        <?php echo $block->getBlockHtml('formkey') ?>
        <legend>Add to cart</legend>
        <label>SKU: <input id="input-sku" type="text" name="SKU" autocomplete="off" list="skus" required></label>
        <label class="qty-own-class">QTY: <input id="input-qty" type="text" name="QTY" autocomplete="off"
                                                 required></label>
        <datalist id="skus">
        </datalist>
    </fieldset>
    <button class="button-own-class" type="button" id="submitAdding">Add</button>
</form>




